{% set version = "2020.1.30" %}
{% set pckname = "sound_field_analysis" %}
{% set sha256 = "3cd7a98913f9489aa2900a14a97ed8b3b56cb827b66fe60b3dc41a77bfc5d97a" %}

package:
  name: {{ pckname }}
  version: {{ version }}

source:
  fn: {{ pckname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/{{ pckname }}/{{ pckname }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - plotly

test:
  imports:
    - sound_field_analysis

about:
  home: https://github.com/QULab/sound_field_analysis-py/
  license: GPL-3.0
  summary: 'Analyze, visualize and process sound field data recorded by spherical microphone arrays'
  description: |
    The sound_field_analysis toolbox (short: sfa) is a Python port
    of the Sound Field Analysis Toolbox (SOFiA) toolbox, originally
    by Benjamin Bernschuetz. The main goal of the sfa toolbox is to
    analyze, visualize and process sound field data recorded by spherical
    microphone arrays. Furthermore, various types of testdata may be
    generated to evaluate the implemented functions.
  doc_url: https://qulab.github.io/sound_field_analysis-py/
  dev_url: https://github.com/QULab/sound_field_analysis-py/

extra:
  recipe-maintainers:
    - chohner
