travis:
  secure:
    BINSTAR_TOKEN: l/sgeglmNfs/oQn7+ScMNOCYUd3vz/an9X0JPxYtZa0Km/PdWKAyRWIuno7hWJmTvJXy6GmF3pLv4sB67qK4Lan36s945IDDnAYXsTELmLqnktqWVSLMTM/BCsIPKIVQiGYxizVtKnO3fmDzTYBOs7M0n5ieU0xRfYXYQCQeSUAeUY9ARxA4Y4sznbDvvnaWB4foPHHauCwNj8zW9qbVlx8P6slp1H8BuqpcuD1THBYn4TXDx7wChCQr4aXmj/8GXqCWZT8TXINVNFAbN2zUEh4sdGYbvmqWiK0eMtwZUt2emMdoL845YtVwwlnoW6Vw+qROFNxQxJJYFjOx0jqmk7i0fBhMwcWij6U3BpwDMpR4avCoCuTwOOy8AFK+RCABH58htmD8luh/hklhlIjPaONaLLiCxWDJjDP54Lxt4IadYb7f6D0WWNAGl3fwlYSNyNqXONxaP9hyXmFaA9U3InIfR3okEf69PgRr4P3PzLVypouNDO7/QC4cs3PrL/7yBqcB17+6UggC5idfIY/7mEpw6rpX5EGKBh2LcOOxoHlrdH4D0zXXfKwx93iJ9xK9/+4XAG7qSO7Io8xmWc98F0pKvgudIWQ21ixwVV+UU7Gu4AMsQHk+m5zZQOkCAmAVRhOXcxjduYhmA5ChcJJrOxZNWzPoDomTzM1Yb4GYA4M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
