travis:
  secure:
    BINSTAR_TOKEN: jJjnJiaKJeD0goFfe7Vb985AJKz191BQYg/348DVHBVjRiDn0TJ2fdDL0GYS3InxQK7EllqFt4YBQTlQH0XjC40B7h3PjCneEFv5QWKzbjyHsKB/Sj/2Y1OQxQr8f3yOs9IJo57wJk6Il3R1Eb4Zqs3hiZ6/WJUlA6ZbpmlGTlTxK+2YsdqeYOaT6nzqehuk3KHrWCMpQidxjXVnIplbWvJcLJCLaoWZ1WWgNQwPOxR3qDoR7PCIAmW5p+E0Alk3d4xZaEpnXmE3kU4dgEcsw9HcngnvyZcHvIWXvjTVMFo1JREAtKGO4AsapO3bri8P6KvCY/2hmCDRrNe82xG1lR+96bZZwFmx94ISEzVSr2Q20sxltzKl8xRms/WthLHvEdL4N5/bdDNUynarb3IZamT+1iObuuh0qOOBO6sgInlu6QmrBa6aPOrrfy+MOcW29TQnFWJhcVmP0YSajqGC9PFmifuYcYghOj3do0ooz2DY/FRxi8f2Ab+HZM/b7DC1qxRbehv7gqE/5N1WdNQ8yfQ7rPhhAN5FegKIyQDH4KDU22h6bsonLOtTDbaH3NDro7aYQR9Dwk9gIYRnCyV+Yv6aAjFnA0UgoRgFZu4fQ2rS/YBEp49097b5gWvIP04XC0UWg6wWT3xwR8iHii7kisUW7h2VjSThOiAc5MoMEv0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
